### PR TITLE
Tweak loadgoa module to handle plant goa data file

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
I still need to run tests but just wanted a quick review of the design update to the module to load goa annotations.

**Comment by EvanDietzMorris** [comment]
See: #99

**Review by PhillipsOwen — COMMENTED** [review]
i think you should create another file for your plant data parsing (peer to loadGOA.py).

i am not sure if this data is appropriate for the current aggregated graphs.

**Comment by EvanDietzMorris** [comment]
@PhillipsOwen That is what I already did in the pull request mentioned above. #99

**Pull request merged**
